// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryhqmxcnirtzsgvmibnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5aHFteGNuaXJ0enNndm1pYm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NzAxOTUsImV4cCI6MjA1NjU0NjE5NX0.EVgs5okBIfA3cPXzAz34JQg2pRPsDNZHx6MCukteJ10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);